spring:
  application:
    name: gateway
  cloud:
   gateway:
     routes:
       - id: product
         uri: http://localhost:8081
         predicates:
           - Path=/product/**
         filters:
           - AuthenticationFilter


       - id: shop
         uri: http://localhost:8082
         predicates:
           - Path=/shopapi/**
         filters:
           - AuthenticationFilter

       - id: identity
         uri: http://localhost:9898
         predicates:
           - Path=/auth/**
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      